name: my_test
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Gavin King <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.3.0
